# Musa 21i-1206 SE-P
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend
  namespace: exam
  labels:
    app: my-backend
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend
  template:
    metadata:
      labels:
        app: my-backend
        annotations: 
          "Musa 21i-1206 SE-P":"backend"
    spec:
      containers:
      - name: auth
        image: musahs/scd_final_exam:auth
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
        readinessProbe:
          httpGet:
            path: /ready
            port: 4000
      - name: classrooms
        image: musahs/scd_final_exam:classrooms
        ports:
        - containerPort: 4001
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 4001
        readinessProbe:
          httpGet:
            path: /ready
            port: 4001
      - name: event-bus
        image: musahs/scd_final_exam:event-bus
        ports:
        - containerPort: 4009
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 4009
        readinessProbe:
          httpGet:
            path: /ready
            port: 4009
      - name: post
        image: musahs/scd_final_exam:post
        ports:
        - containerPort: 4002
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 4002
        readinessProbe:
          httpGet:
            path: /ready
            port: 4002
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 27017
        readinessProbe:
          httpGet:
            path: /ready
            port: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc