apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
  namespace: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-frontend
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      containers:
      - name: client
        image: musahs/scd_final_exam:client
        ports:
        - containerPort: 80