apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: exam
spec:
  type: NodePort
  selector:
    app: my-backend
    tier: backend
    component: auth
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: classrooms-service
  namespace: exam
spec:
  type: NodePort
  selector:
    app: my-backend
    tier: backend
    component: classrooms
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
  namespace: exam
spec:
  type: NodePort
  selector:
    app: my-backend
    tier: backend
    component: event-bus
  ports:
    - protocol: TCP
      port: 4009
      targetPort: 4009

---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: exam
spec:
  type: NodePort
  selector:
    app: my-backend
    tier: backend
    component: post
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: exam
spec:
  type: NodePort
  selector:
    app: my-frontend
    tier: backend
    component: post
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 8080